@startuml
class Solution45{
    main(String[])
    'wordFinder app = new wordFinder()
    'app.read(String)
    'app.parse()
    'app.write()
}

class wordFinder{
    'attributes
    - StringBuilder fileText

    'methods
    + wordFinder()

    + read(String): boolean
    + parse(): boolean
    + write(): boolean
}

Solution45 --o wordFinder
@enduml